### ISSUE TITLE
should i use model's method directly in controller ?

### ISSUE THREAD

**Issue by devmark** [yellowflag/cribbb#12]
find() , all() returning an instance of model . in controller still coupled to the Model Class. so should change different object?

controller:
~~~~
//get a record from repository
$user = Repository::find(1);
// if execute save(), it will call repository which binding eloquent
$user->save()
~~~~
if i replace Eloquent model to fluent
i pretend fluent model dont have save method,it should not work perfect if i need to change other model right?

any suggestion ?
thanks

this is a post controller copy from https://github.com/BootstrapCMS/CMS
~~~~
        $post = PostRepository::find($id);
        $this->checkPost($post);
        $post->update($input);
~~~~

**Comment by philipbrown** [comment]
Yeah that looks fine to me. Calling `save()` doesn't bind you to Eloquent, it binds you to an interface that has a `save()` method.

**Comment by elceka** [comment]
Technically is it OK, but then you don't need a DDD. :)
